"""
Markdown rendering for the amendment export package.
Pure functions — no DB calls; the caller assembles the data and we just
template the output. Deterministic, no LLM involved.
"""
from __future__ import annotations
from datetime import datetime
from typing import Iterable

from app.schemas import AmendmentChange


def _fmt_dt(dt: datetime) -> str:
    """Render a datetime in a human-readable, document-ish format."""
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def _risk_band(score: int) -> str:
    if score >= 60:
        return "HIGH"
    if score >= 30:
        return "MEDIUM"
    return "LOW"


def render_change(idx: int, change: AmendmentChange) -> str:
    """Render a single Change N section."""
    return f"""## Change {idx} — {change.section}

**Clause ID:** `{change.clause_id}`
**Risk before:** {change.risk_before}/100 ({_risk_band(change.risk_before)})
**Risk after:** {change.risk_after}/100 ({_risk_band(change.risk_after)})
**Fix applied:** {change.label}

### Original text

> ~~{change.original_text}~~

### Amended text

> {change.new_text}

### Rationale

{change.rationale}

### Audit

- Suggested by: Amendment-Risk Agent
- Accepted by: medical_writer@iqvia.com
- Accepted at: {_fmt_dt(change.accepted_at)}

---
"""


def render_markdown(
    *,
    protocol_id: str,
    protocol_title: str,
    from_version: str,
    to_version: str,
    overall_risk_before: int,
    overall_risk_after: int,
    changes: Iterable[AmendmentChange],
    generated_at: datetime,
) -> str:
    """Assemble the full amendment package as a markdown string."""
    changes_list = list(changes)
    n_changes = len(changes_list)

    header = f"""# Protocol Amendment Package

**Protocol:** {protocol_title}
**Protocol ID:** `{protocol_id}`
**Version change:** {from_version} → {to_version}
**Generated:** {_fmt_dt(generated_at)}
**Amendment-Risk reduction:** {overall_risk_before}% → {overall_risk_after}%

---

## Summary

This amendment package contains **{n_changes} accepted clause modification{'s' if n_changes != 1 else ''}**, reducing the overall Amendment-Risk score from **{overall_risk_before}%** to **{overall_risk_after}%**.

All HIGH-risk clauses identified in {from_version} have been addressed. MEDIUM and LOW risks remain for reviewer consideration.

---
"""

    changes_md = "\n".join(render_change(i + 1, c) for i, c in enumerate(changes_list))

    footer = """## Methodology

The Amendment-Risk Agent analyzes each clause against a corpus of 50 historical protocol amendment patterns (Tufts CSDD-modeled), scoring on six dimensions: pattern match strength, therapeutic area fit, operational complexity, inclusion restrictiveness, endpoint instrument validation, and visit burden.

Suggested fixes are generated by the Amendment-Risk Agent with grounding in the matched amendment patterns. Each accepted fix is logged with original text, amended text, predicted risk reduction, and reviewer attestation.

---

## Sign-off

This amendment package is ready for:

- [ ] Medical Director review
- [ ] Regulatory Affairs review
- [ ] Statistician review
- [ ] Sponsor sign-off

**Next step:** Route to lead reviewer for formal protocol amendment processing.

---

_Generated by IQVIA Protocol Co-Pilot · v1.0_
"""

    return header + "\n" + changes_md + "\n" + footer
